title: 岁月尘沙
author: Homary
description: 上天不会创造人上人,也不会创造人下人.

highlighter: null
permalink: /:title
intensedebate_comments: true
url:
baseurl:

# Custom options:
# color_scheme: azul|ruby|amber|avocado
# color_scheme: avocado
